#!/bin/bash

echo "# Body Parameters Implementation Check"
echo ""
echo "## Checking which body parameters are implemented in OvhPrivateCloud.node.ts"
echo ""

# List of all body parameters from the API
params=(
"backupDays"
"backupDurationInReport"
"backupJobName"
"backupOffer"
"backupRepositoryName"
"backupSizeInReport"
"baseDnForGroups"
"baseDnForUsers"
"bypassGuestOsFamilyCheck"
"canAddRessource"
"canManageIpFailOvers"
"canManageNetwork"
"canManageRights"
"commentary"
"commercialRangeName"
"contactAdmin"
"contactBilling"
"contactTech"
"datastore"
"description"
"diskSizeInReport"
"domainAlias"
"domainName"
"duration"
"email"
"encryptionRight"
"executionDate"
"expirationDate"
"filerId"
"filerType"
"firstName"
"fullAdminRo"
"fullDayInReport"
"futureUse"
"groupName"
"hostId"
"ip"
"kind"
"kmsLicense"
"label"
"lastName"
"ldapHostname"
"ldapTcpPort"
"localVraNetwork"
"macAddress"
"mailAddress"
"name"
"netmask"
"network"
"networkRole"
"newDatacenterId"
"newEndpointPublicIp"
"noSsl"
"nsxRight"
"objectType"
"option"
"ovhEndpointIp"
"password"
"phoneNumber"
"portgroup"
"preSharedKey"
"primaryEndpointIp"
"propagate"
"reason"
"receiveAlerts"
"release"
"remoteEndpointInternalIp"
"remoteEndpointPublicIp"
"remoteVraNetwork"
"remoteZvmInternalIp"
"resourcesSize"
"restorePointId"
"restorePointInReport"
"right"
"scheduleHour"
"secondaryDatacenterId"
"secondaryEndpointIp"
"secondaryServiceName"
"servicePort"
"size"
"sslThumbprint"
"sslV3"
"streamId"
"token"
"tokenValidator"
"type"
"userAccessPolicy"
"userLimitConcurrentSession"
"userLogoutPolicy"
"username"
"userSessionTimeout"
"vendorId"
"version"
"vmId"
"vmNetworkRole"
"vmwareClusterId"
"vmwareObjectId"
"vrackName"
)

echo "### Parameters found in implementation:"
echo ""
for param in "${params[@]}"; do
    if grep -q "'$param'" nodes/OvhPrivateCloud/OvhPrivateCloud.node.ts || grep -q "\"$param\"" nodes/OvhPrivateCloud/OvhPrivateCloud.node.ts; then
        echo "✓ $param"
    fi
done

echo ""
echo "### Parameters NOT found in implementation:"
echo ""
for param in "${params[@]}"; do
    if ! grep -q "'$param'" nodes/OvhPrivateCloud/OvhPrivateCloud.node.ts && ! grep -q "\"$param\"" nodes/OvhPrivateCloud/OvhPrivateCloud.node.ts; then
        echo "✗ $param"
    fi
done